"""empty message

Revision ID: 0d4c2d8075b7
Revises: 
Create Date: 2023-11-23 17:07:20.434039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4c2d8075b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('groups',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id_organizer', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('languages', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizer'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_group'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_languages',
    sa.Column('id_user_language', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('english', 'spanish', 'french', 'italian', 'german', 'portuguese', 'russian', 'arabic', 'japanese', 'chinese', name='enum_languages'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_language')
    )
    op.create_table('events',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('attendee', sa.Boolean(), nullable=True),
    sa.Column('event_capacity', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id_group'], ),
    sa.PrimaryKeyConstraint('id_event'),
    sa.UniqueConstraint('name')
    )
    op.create_table('members_group',
    sa.Column('id_member_group', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id_group'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_member_group')
    )
    op.create_table('events_attendee',
    sa.Column('id_event_attendee', sa.Integer(), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_event'], ['events.id_event'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_event_attendee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_attendee')
    op.drop_table('members_group')
    op.drop_table('events')
    op.drop_table('user_languages')
    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###
